# Generated by Django 4.2.3 on 2024-06-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(max_length=999)),
                ('device', models.CharField(max_length=999)),
            ],
        ),
    ]
