# Generated by Django 5.0.6 on 2024-08-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0004_user_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='ip',
            field=models.CharField(default='', max_length=99),
            preserve_default=False,
        ),
    ]
