# Generated by Django 5.0.6 on 2024-08-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0006_alter_user_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userroles',
            name='role',
            field=models.CharField(choices=[('seller', 'Seller'), ('customer', 'Customer')], max_length=20),
        ),
    ]
