# Generated by Django 4.2.3 on 2024-04-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('004', 'Shipping'), ('002', 'Order Confirmed'), ('005', 'Delivered'), ('003', 'In Process'), ('001', 'Order Pending')], max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_type',
            field=models.CharField(blank=True, choices=[('001', 'Normal'), ('003', 'Varient'), ('002', 'Template')], default='001', max_length=999, null=True),
        ),
    ]
