# Generated by Django 4.2.3 on 2023-12-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_net_price_product_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='product',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.CharField(max_length=9999, null=True),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
