# Generated by Django 5.0.6 on 2024-07-04 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_value_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-modified']},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['-modified']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-modified']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-modified']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-modified']},
        ),
        migrations.AlterModelOptions(
            name='orderitems',
            options={'ordering': ['-modified']},
        ),
        migrations.AlterModelOptions(
            name='orderreview',
            options={'ordering': ['-modified']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-modified']},
        ),
        migrations.AlterModelOptions(
            name='productcategorycommission',
            options={'ordering': ['-modified']},
        ),
        migrations.AlterModelOptions(
            name='productdiscount',
            options={'ordering': ['-modified']},
        ),
        migrations.AlterModelOptions(
            name='productmedia',
            options={'ordering': ['-modified']},
        ),
        migrations.AlterModelOptions(
            name='productvariantattribute',
            options={'ordering': ['-modified']},
        ),
        migrations.AlterModelOptions(
            name='sellerorder',
            options={'ordering': ['-modified']},
        ),
    ]
