# Generated by Django 4.2.3 on 2024-04-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_order_order_status_alter_product_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('001', 'Order Pending'), ('002', 'Order Confirmed'), ('003', 'In Process'), ('004', 'Shipping'), ('005', 'Delivered')], max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_type',
            field=models.CharField(blank=True, choices=[('001', 'Normal'), ('002', 'Template'), ('003', 'Varient')], default='001', max_length=999, null=True),
        ),
    ]
