# Generated by Django 4.2.3 on 2024-04-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_is_digital'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomersOrdersHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=999)),
                ('order_id', models.CharField(max_length=999)),
                ('total_amount', models.CharField(max_length=999)),
                ('total_qty', models.CharField(max_length=999)),
                ('payment_method', models.CharField(max_length=999)),
                ('delivery_status', models.CharField(max_length=999)),
                ('delivery_address', models.CharField(max_length=999)),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
