# Generated by Django 4.2.3 on 2024-04-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_customersordershistory_alter_cart_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_digital',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
