# Generated by Django 4.2.3 on 2024-01-01 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_customer_order_orderitems_cartitem_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='customer_name',
        ),
    ]
