# Generated by Django 5.0.6 on 2024-08-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_delivery_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomersOrdersHistory',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('001', 'Order Pending'), ('002', 'Order Confirmed'), ('003', 'In Process'), ('004', 'Shipping'), ('005', 'Delivered'), ('006', 'Cancelled')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.DeleteModel(
            name='SellerOrder',
        ),
    ]
