# Generated by Django 4.2.3 on 2024-04-17 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_category_is_digital_alter_order_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='is_digital',
            new_name='digital',
        ),
    ]
