# Generated by Django 4.2.3 on 2024-01-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_name_customer_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
