# Generated by Django 4.2.3 on 2024-04-26 21:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_is_digital_category_digital'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('001', 'Order Pending'), ('002', 'Order Confirmed'), ('003', 'In Process'), ('004', 'Shipping'), ('005', 'Delivered'), ('006', 'Cancelled')], max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default=models.CharField(max_length=9999), null=True),
        ),
        migrations.CreateModel(
            name='ProductCategoryCommission',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=10000, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
