# Generated by Django 5.0.6 on 2024-08-28 14:47

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_delete_customersordershistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerOrder',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=10000, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('001', 'Order Pending'), ('002', 'Order Confirmed'), ('003', 'In Process'), ('004', 'Shipping'), ('005', 'Delivered'), ('006', 'Cancelled')], default='001', max_length=50, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('order_items', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=999), size=None)),
                ('order_id', models.CharField(max_length=10000)),
                ('shipping_id', models.CharField(max_length=10000)),
                ('total', models.DecimalField(decimal_places=2, max_digits=11)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer')),
                ('delivery_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.useraddress')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.seller')),
            ],
            options={
                'ordering': ['-modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SellerOrderItems',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=10000, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=11)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=11)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.sellerorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'ordering': ['-modified'],
                'abstract': False,
            },
        ),
    ]
