# Generated by Django 4.2.3 on 2024-04-26 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_commission_alter_order_order_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='commission',
            new_name='commission_rate',
        ),
    ]
