# Generated by Django 5.0.6 on 2024-09-05 21:03

from django.db import migrations, models
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_sellerorder_sellerorderitems"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sellerorder",
            old_name="total",
            new_name="grand_total",
        ),
        migrations.AddField(
            model_name="sellerorder",
            name="total_qty",
            field=models.DecimalField(
                decimal_places=2, default=Decimal(0), max_digits=11
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("001", "Order Pending"),
                    ("002", "Order Confirmed"),
                    ("003", "In Process"),
                    ("004", "Shipping"),
                    ("005", "Delivered"),
                    ("006", "Cancelled"),
                    ("007", "Refunded"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="orderitems",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("001", "Order Pending"),
                    ("002", "Order Confirmed"),
                    ("003", "In Process"),
                    ("004", "Shipping"),
                    ("005", "Delivered"),
                    ("006", "Cancelled"),
                    ("007", "Refunded"),
                ],
                max_length=999,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sellerorder",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("001", "Order Pending"),
                    ("002", "Order Confirmed"),
                    ("003", "In Process"),
                    ("004", "Shipping"),
                    ("005", "Delivered"),
                    ("006", "Cancelled"),
                    ("007", "Refunded"),
                ],
                default="001",
                max_length=50,
                null=True,
            ),
        ),
    ]
