# Generated by Django 4.2.3 on 2024-01-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_cart_total_amount_alter_cart_total_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('004', 'Shipping'), ('003', 'In Process'), ('005', 'Delivered'), ('001', 'Order Pending'), ('002', 'Order Confirmed')], max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_qty',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='qty',
            field=models.FloatField(default=1),
        ),
    ]
