# Generated by Django 5.0.6 on 2024-09-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_total_sellerorder_grand_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerorder',
            name='order_id',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
