# Generated by Django 4.2.3 on 2024-04-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_commission_product_commission_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
