# Generated by Django 4.2.3 on 2024-04-26 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategorycommission',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.category'),
        ),
    ]
