# Generated by Django 4.2.3 on 2024-01-09 19:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_order_order_status_alter_order_total_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('002', 'Order Confirmed'), ('005', 'Delivered'), ('003', 'In Process'), ('004', 'Shipping'), ('001', 'Order Pending')], max_length=999, null=True),
        ),
    ]
