# Generated by Django 4.2.3 on 2024-01-09 19:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_order_order_id_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=uuid.uuid4, max_length=999, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('003', 'In Process'), ('001', 'Order Pending'), ('002', 'Order Confirmed'), ('004', 'Shipping'), ('005', 'Delivered')], max_length=999, null=True),
        ),
    ]
