# Generated by Django 5.0.6 on 2024-09-05 21:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_sellerorder_order_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SellerOrderItems',
            new_name='SellerDigitalOrderItem',
        ),
        migrations.CreateModel(
            name='SellerDigitalOrder',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=10000, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('001', 'Pending'), ('002', 'Processing'), ('003', 'Completed'), ('004', 'Cancelled'), ('005', 'Refunded')], default='001', max_length=50, null=True)),
                ('order_id', models.CharField(max_length=10000, null=True)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=11)),
                ('total_qty', models.DecimalField(decimal_places=2, max_digits=11)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.seller')),
            ],
            options={
                'ordering': ['-modified'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='sellerdigitalorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.sellerdigitalorder'),
        ),
        migrations.CreateModel(
            name='SellerOrderItem',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=10000, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=11)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=11)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.sellerorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'ordering': ['-modified'],
                'abstract': False,
            },
        ),
    ]
