# Generated by Django 4.2.3 on 2024-05-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_product_commission_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreErrorLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField()),
            ],
        ),
    ]
