# Generated by Django 4.2.3 on 2024-05-12 21:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_storeerrorlogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=10000, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productdiscount',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
