# Generated by Django 4.2.3 on 2024-01-09 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_order_order_status_alter_order_total_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='grand_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('004', 'Shipping'), ('005', 'Delivered'), ('001', 'Order Pending'), ('003', 'In Process'), ('002', 'Order Confirmed')], max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_qty',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='store.order'),
        ),
    ]
