# Generated by Django 5.0.6 on 2024-09-22 18:20

import django.contrib.postgres.fields
import django.db.models.deletion
import server.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_cancelordermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalOrder',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=10000, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('order_id', models.CharField(default=server.utils.generate_snf_id, max_length=999, unique=True)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('order_status', models.CharField(blank=True, choices=[('001', 'Order Placed'), ('002', 'Order Processing'), ('003', 'Order Completed'), ('004', 'Cancelled')], default='001', max_length=50, null=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('payment_method', models.CharField(blank=True, max_length=99, null=True)),
                ('total_qty', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=12)),
                ('grand_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer')),
            ],
            options={
                'ordering': ['-modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DigitalOrderItem',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=10000, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('has_review', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('001', 'Order Placed'), ('002', 'Order Processing'), ('003', 'Order Completed'), ('004', 'Cancelled')], max_length=999, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.digitalorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'ordering': ['-modified'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CancelOrderModel',
        ),
        migrations.DeleteModel(
            name='StoreErrorLogs',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='item',
            new_name='product',
        ),
        migrations.AddField(
            model_name='sellerdigitalorder',
            name='order_items',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=299), null=True, size=1000),
        ),
        migrations.AlterField(
            model_name='sellerdigitalorder',
            name='status',
            field=models.CharField(choices=[('001', 'Order Placed'), ('002', 'Order Processing'), ('003', 'Order Completed'), ('004', 'Cancelled')], default='001', max_length=50),
        ),
        migrations.AlterField(
            model_name='sellerorder',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
