# Generated by Django 5.0.6 on 2024-09-24 21:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_sellerdigitalorder_grand_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=299)),
                ('cancelled_by', models.CharField(blank=True, max_length=200, null=True)),
                ('cancellation_reason', models.CharField(max_length=1000)),
                ('notes', models.TextField()),
                ('cancelled_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-cancelled_at'],
            },
        ),
        migrations.AlterField(
            model_name='digitalorderitem',
            name='status',
            field=models.CharField(blank=True, choices=[('001', 'Order Placed'), ('002', 'Order Processing'), ('003', 'Order Completed'), ('004', 'Cancelled')], default='001', max_length=999, null=True),
        ),
    ]
