# Generated by Django 4.2.3 on 2024-01-15 22:11

from django.db import migrations, models
import server.utils


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=server.utils.generate_order_id, max_length=999, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('005', 'Delivered'), ('002', 'Order Confirmed'), ('003', 'In Process'), ('001', 'Order Pending'), ('004', 'Shipping')], max_length=999, null=True),
        ),
    ]
