# Generated by Django 5.0.6 on 2024-10-03 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_rename_has_review_digitalorderitem_reviewed_by_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderreview',
            name='order_id',
            field=models.CharField(default=True, max_length=999),
            preserve_default=False,
        ),
    ]
