# Generated by Django 4.2.3 on 2024-01-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_order_order_id_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('002', 'Order Confirmed'), ('004', 'Shipping'), ('003', 'In Process'), ('005', 'Delivered'), ('001', 'Order Pending')], max_length=999, null=True),
        ),
    ]
