# Generated by Django 5.0.6 on 2024-10-11 22:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_orderreview_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfileRequest',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=10000, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('store_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('business_license', models.FileField(blank=True, null=True, upload_to='business_licenses/')),
                ('description', models.TextField(blank=True, null=True)),
                ('request_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-modified'],
                'abstract': False,
            },
        ),
    ]
