# Generated by Django 5.0.6 on 2024-10-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_sellerprofilerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofilerequest',
            name='website_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
