# Generated by Django 5.0.6 on 2024-10-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_sellerprofilerequest_website_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofilerequest',
            name='email',
            field=models.CharField(),
        ),
    ]
