# Generated by Django 4.2.3 on 2024-01-19 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_productattribute_product_item_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('002', 'Order Confirmed'), ('004', 'Shipping'), ('005', 'Delivered'), ('001', 'Order Pending'), ('003', 'In Process')], max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_type',
            field=models.CharField(choices=[('002', 'Template'), ('001', 'Normal'), ('003', 'Varient')], default='001', max_length=999),
        ),
    ]
