# Generated by Django 5.0.6 on 2024-10-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_sellerprofilerequest_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofilerequest',
            name='seller_user',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
