# Generated by Django 5.0.6 on 2024-10-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_sellerprofilerequest_seller_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofilerequest',
            name='user_password',
            field=models.CharField(blank=True, max_length=299, null=True),
        ),
    ]
