# Generated by Django 4.2.3 on 2024-01-19 22:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_product_template_alter_order_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariantattribute',
            name='product',
            field=models.ForeignKey(default=datetime.datetime(2024, 1, 19, 22, 27, 10, 173499, tzinfo=datetime.timezone.utc), on_delete=django.db.models.deletion.CASCADE, to='store.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('001', 'Order Pending'), ('004', 'Shipping'), ('002', 'Order Confirmed'), ('003', 'In Process'), ('005', 'Delivered')], max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_type',
            field=models.CharField(choices=[('001', 'Normal'), ('002', 'Template'), ('003', 'Varient')], default='001', max_length=999),
        ),
    ]
