# Generated by Django 4.2.3 on 2024-01-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_productvariantattribute_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('002', 'Order Confirmed'), ('003', 'In Process'), ('001', 'Order Pending'), ('005', 'Delivered'), ('004', 'Shipping')], max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_type',
            field=models.CharField(choices=[('002', 'Template'), ('001', 'Normal'), ('003', 'Varient')], default='001', max_length=999),
        ),
    ]
