# Generated by Django 4.2.3 on 2024-01-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_alter_order_order_status_alter_product_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('001', 'Order Pending'), ('003', 'In Process'), ('004', 'Shipping'), ('002', 'Order Confirmed'), ('005', 'Delivered')], max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_type',
            field=models.CharField(choices=[('003', 'Varient'), ('001', 'Normal'), ('002', 'Template')], default='001', max_length=999),
        ),
    ]
