# Generated by Django 4.2.3 on 2024-01-28 16:52

from django.db import migrations, models
import django.db.models.deletion
import server.utils


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_alter_order_order_status_alter_product_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=server.utils.generate_snf_id, max_length=999, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('002', 'Order Confirmed'), ('004', 'Shipping'), ('001', 'Order Pending'), ('005', 'Delivered'), ('003', 'In Process')], max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_type',
            field=models.CharField(blank=True, choices=[('002', 'Template'), ('003', 'Varient'), ('001', 'Normal')], default='001', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
