# Generated by Django 4.2.3 on 2024-01-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_alter_cartitem_amount_alter_cartitem_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('001', 'Order Pending'), ('002', 'Order Confirmed'), ('004', 'Shipping'), ('003', 'In Process'), ('005', 'Delivered')], max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_type',
            field=models.CharField(blank=True, choices=[('001', 'Normal'), ('003', 'Varient'), ('002', 'Template')], default='001', max_length=999, null=True),
        ),
    ]
