# Generated by Django 4.2.3 on 2024-03-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_orderitems_has_review_orderreview_order_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='has_review',
        ),
        migrations.RemoveField(
            model_name='orderreview',
            name='order_item',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('001', 'Order Pending'), ('002', 'Order Confirmed'), ('005', 'Delivered'), ('003', 'In Process'), ('004', 'Shipping')], max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_type',
            field=models.CharField(blank=True, choices=[('003', 'Varient'), ('001', 'Normal'), ('002', 'Template')], default='001', max_length=999, null=True),
        ),
    ]
