# Generated by Django 4.2.3 on 2024-03-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_remove_orderitems_has_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('005', 'Delivered'), ('002', 'Order Confirmed'), ('003', 'In Process'), ('001', 'Order Pending'), ('004', 'Shipping')], max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_type',
            field=models.CharField(blank=True, choices=[('003', 'Varient'), ('002', 'Template'), ('001', 'Normal')], default='001', max_length=999, null=True),
        ),
    ]
