# Generated by Django 4.2.3 on 2024-03-13 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_alter_order_order_status_alter_product_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='has_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderreview',
            name='order_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.orderitems'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('005', 'Delivered'), ('001', 'Order Pending'), ('002', 'Order Confirmed'), ('004', 'Shipping'), ('003', 'In Process')], max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_type',
            field=models.CharField(blank=True, choices=[('002', 'Template'), ('003', 'Varient'), ('001', 'Normal')], default='001', max_length=999, null=True),
        ),
    ]
