# Generated by Django 4.2.3 on 2024-03-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_alter_order_delivery_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=999)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('001', 'Order Pending'), ('002', 'Order Confirmed'), ('005', 'Delivered'), ('004', 'Shipping'), ('003', 'In Process')], max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_type',
            field=models.CharField(blank=True, choices=[('002', 'Template'), ('003', 'Varient'), ('001', 'Normal')], default='001', max_length=999, null=True),
        ),
    ]
