# Generated by Django 4.2.3 on 2024-03-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_modelmedia_alter_order_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('004', 'Shipping'), ('001', 'Order Pending'), ('005', 'Delivered'), ('003', 'In Process'), ('002', 'Order Confirmed')], max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_type',
            field=models.CharField(blank=True, choices=[('001', 'Normal'), ('002', 'Template'), ('003', 'Varient')], default='001', max_length=999, null=True),
        ),
    ]
