# Generated by Django 4.2.3 on 2024-03-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_alter_order_order_status_alter_product_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('002', 'Order Confirmed'), ('005', 'Delivered'), ('003', 'In Process'), ('001', 'Order Pending'), ('004', 'Shipping')], max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_type',
            field=models.CharField(blank=True, choices=[('002', 'Template'), ('003', 'Varient'), ('001', 'Normal')], default='001', max_length=999, null=True),
        ),
    ]
