# Generated by Django 4.2.3 on 2024-03-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_alter_order_order_status_alter_product_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelmedia',
            name='field_id',
            field=models.CharField(default='test', max_length=999),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('005', 'Delivered'), ('001', 'Order Pending'), ('004', 'Shipping'), ('002', 'Order Confirmed'), ('003', 'In Process')], max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_type',
            field=models.CharField(blank=True, choices=[('003', 'Varient'), ('001', 'Normal'), ('002', 'Template')], default='001', max_length=999, null=True),
        ),
    ]
