# Generated by Django 4.2.3 on 2024-03-29 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_modelmedia_field_id_alter_order_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('005', 'Delivered'), ('004', 'Shipping'), ('001', 'Order Pending'), ('002', 'Order Confirmed'), ('003', 'In Process')], max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_type',
            field=models.CharField(blank=True, choices=[('002', 'Template'), ('003', 'Varient'), ('001', 'Normal')], default='001', max_length=999, null=True),
        ),
    ]
