# Generated by Django 4.2.3 on 2024-04-03 22:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_alter_order_order_status_alter_product_item_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEntry',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=10000, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('party', models.CharField(max_length=999)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(max_length=200)),
                ('reference_id', models.CharField(max_length=200)),
                ('currency', models.CharField(max_length=200)),
                ('is_paid', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('003', 'In Process'), ('004', 'Shipping'), ('002', 'Order Confirmed'), ('001', 'Order Pending'), ('005', 'Delivered')], max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_type',
            field=models.CharField(blank=True, choices=[('003', 'Varient'), ('001', 'Normal'), ('002', 'Template')], default='001', max_length=999, null=True),
        ),
    ]
