# Generated by Django 4.2.3 on 2024-04-07 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0053_alter_category_image_alter_order_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('003', 'In Process'), ('001', 'Order Pending'), ('004', 'Shipping'), ('002', 'Order Confirmed'), ('005', 'Delivered')], max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_type',
            field=models.CharField(blank=True, choices=[('003', 'Varient'), ('002', 'Template'), ('001', 'Normal')], default='001', max_length=999, null=True),
        ),
    ]
